name: Publish package to GitHub Packages
on:
  push: [ demo ]
  #release:
   # types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: gradle -Pversion=${{ github.event.release.tag_name }} build publish
        env:
          GITHUB_TOKEN: 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
